server:
  port: 8080

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
#      driver-class-name: org.sqlite.JDBC
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:sqlite::resource:database/todo.db
#      jdbc-url: jdbc:sqlite::resource:database/todo.db


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type:
    aliases-package: com.todo.mapper

#logging:
#  config: classpath:logback-spring.xml

logging:
  level:
    org.hibernate.SQL: debug
