server:
  port: 8080

spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      driver-class-name: org.sqlite.JDBC
      jdbc-url: jdbc:sqlite::resource:database/todo.db


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type:
    aliases-package: com.todo.mapper

